# Generated by Django 4.1.3 on 2022-11-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Captain', models.CharField(max_length=128)),
                ('age_Captain', models.CharField(max_length=32)),
                ('dec_Captain', models.TextField()),
                ('trip_time', models.DateTimeField()),
            ],
        ),
    ]
