# Generated by Django 4.1.3 on 2022-11-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeaTripesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titile', models.CharField(max_length=128)),
                ('dec', models.TextField()),
                ('date', models.DateTimeField()),
                ('pic', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='captain',
            name='avatar',
            field=models.ImageField(default='images/', upload_to='images/'),
            preserve_default=False,
        ),
    ]
